### ISSUE TITLE
Where does "hide_axis" come from?

### ISSUE THREAD

**Issue by ZeroLi-Bio** [maximemeylan/Meylan_et_al_2022#1]
Hi,

I loaded all packages the script used, but when I ran this line, it came out as: "Error: object 'hide_axis' not found".
Is the hide_axis from "maxime.utils.r"? Or where does it come from?
Thank you!
https://github.com/maximemeylan/Meylan_et_al_2022/blob/91b47a134ceb41ba177889335954eecf6eb61736/02_TLS_imprint_signature.R#L108

Best,

**Comment by maximemeylan** [comment]
Hi, 

Please see the composition of the object below 

`hide_axis <- theme(axis.title.x=element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank(),
      axis.title.y=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank())`
