### ISSUE TITLE
Cannot find Annotation file and "~/script/maxime.utils.r"

### ISSUE THREAD

**Issue by eleozzr** [maximemeylan/Meylan_et_al_2022#2]
Hi Maxime, 
When I try to reproduce the results in your paper,  cannot find the file you used in line 21 in [02_TLS_imprint_signature.R](https://github.com/maximemeylan/Meylan_et_al_2022/blob/main/02_TLS_imprint_signature.R).
```
  annot <- list.files(paste0("/data/visium_ccRCC/annotations/",slide),full.names = T)
```
So, I am considering that could you share your annotation file for slices you included in your paper.  I really appreciate if you can share the file with me (ele717@163.com)
Thank you.

**Comment by maximemeylan** [comment]
Hello, 

I will make the annotations available through the GEO submission. 

Best,
Maxime

**Comment by zhjxiaoruc** [comment]
Wow, that is great, thanks a lot.

**Comment by maximemeylan** [comment]
Annotations are now included as .csv files in each sample directory of submission GSE175540

**Comment by eleozzr** [comment]
Thank you very much. I checked the accession number GSE175540, and I found that you maybe missed the annotation for the sample `ffpe_c_10`.

**Comment by maximemeylan** [comment]
This samples have low tumor content and no TLS, therefore a TLS annotation is not necessary.
