### ISSUE TITLE
Asking for high-resolution histology image

### ISSUE THREAD

**Issue by JingofGao** [maximemeylan/Meylan_et_al_2022#4]
I am very interested in your research work, but I cannot find the high-resolution histology image data in the ccRCC dataset provided by the paper. Please tell me where I can find the data. Thank you very much!

**Comment by maximemeylan** [comment]
Hi please find the high resolution images via the dropbox link below: 

https://www.dropbox.com/scl/fo/w816qkd2fuvjrmcfcxk71/h?rlkey=b0oehyexm03zomed91nf7bmeg&dl=0 

Best,
Maxime

**Comment by JingofGao** [comment]
Thank you for your help. I have another question: How can I convert the ndpi file you provided into a tif file for reading with Python? 
    Now, I've downloaded the ndpi file you provided and opened it with NDPView software, which supports saving ndpi files as tif files. What scale should the output image be to match the coordinates in the tissue_positions_list.csv file from GSE175540?
![Uploading image.png…]()

**Comment by JingofGao** [comment]
- Thank you for your help. I have another question: How can I convert the ndpi file you provided into a tif file for reading with Python? 
- Now, I've downloaded the ndpi file you provided and opened it with NDPView software, which supports saving ndpi files as tif files. What scale should the output image be to match the coordinates in the tissue_positions_list.csv file from GSE175540?
- Here are the details:
![img](https://github.com/JingofGao/hexCNN/blob/main/figures/problem.png?raw=true)

**Comment by maximemeylan** [comment]
Hi, 

Have you tried the python library OpenSlide ? 

https://openslide.org/api/python/

**Comment by JingofGao** [comment]
- Thanks again for your help. I followed your advice and successfully used the OpenSlide library to read histology images. I want to get the local morphological information corresponding to each spot, but I find that the coordinates in the tissue_positions_list.csv file and the pixel in image cannot match well. 
- Here is the detail (small black dots are the coordinates from the tissue_positions_list.csv file):

<div align=center>
<img src="https://github.com/JingofGao/hexCNN/blob/main/figures/problem2.png?raw=true" alt="" width="400">
</div>

- Next is my code:
```python
# read ST
section_id = 'ffpe-C2'
adata = sc.read_visium(path=os.path.join(data_path, section_id), count_file='filtered_feature_bc_matrix.h5')
adata.var_names_make_unique()

x_pixel = adata.obsm["spatial"][:, 1].toarray()
y_pixel = adata.obsm["spatial"][:, 0].toarray()

# read img
img = openslide.open_slide('c_2 FFPE.ndpi')
img_RGB = img.read_region(location=(0,0), level=0, size=img.dimensions)
img_np = np.array(img_RGB)

#Test coordinates on the image
img_new=img_np.copy()
for i in range(len(x_pixel)):
    x=x_pixel[i]
    y=y_pixel[i]
    img_new[int(x-40):int(x+40), int(y-40):int(y+40),:]=0

cv2.imwrite('test.jpg', img_new)
```

**Comment by maximemeylan** [comment]
Hi, 

The dropbox link I provided above are the highest resolution images straight form the microscope. If you need the input images used for space ranger (.tif files) you can download the files below. The tissue_positions_list.csv should then perfectly match. 

https://www.dropbox.com/s/l4z3k7oh0ltmvzl/meylan_2022_visium_raw_images.zip?dl=0 

Best,
Maxime
